import { createElement } from '@lwc/engine-dom';
import DHA_NewStudentRecordForm from 'c/dHA_NewStudentRecordForm';

describe('c-d-h-a-new-student-record-form', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-d-h-a-new-student-record-form', {
            is: DHA_NewStudentRecordForm
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});